#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Install the OpenExpert desktop launcher for the current user (no sudo):
//
//   ~/.local/bin/openexpert-desktop                 Tauri window binary
//   ~/.local/bin/openexpert                         launcher (server + window)
//   ~/.local/share/applications/openexpert.desktop  application-menu entry
//   ~/.local/share/icons/hicolor/512x512/apps/openexpert.png
//
// Usage: node scripts/install-desktop.mjs [--skip-build]

import { spawnSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const home = homedir();
const binDir = join(home, ".local", "bin");
const appsDir = join(home, ".local", "share", "applications");
const hicolorDir = join(home, ".local", "share", "icons", "hicolor");
const iconDir = join(hicolorDir, "512x512", "apps");
const skipBuild = process.argv.includes("--skip-build");

function sh(cmd, args) {
  const r = spawnSync(cmd, args, { cwd: repo, stdio: "inherit" });
  if (r.status !== 0) {
    console.error(`\nFailed: ${cmd} ${args.join(" ")}`);
    process.exit(r.status ?? 1);
  }
}

if (!skipBuild) {
  console.log("· Building the OpenCore CLI…");
  sh("npm", ["run", "build", "--workspace", "@openexpert/opencore"]);
  console.log("· Building the web app…");
  sh("npm", ["run", "build"]);
  console.log("· Building the desktop window (Rust)…");
  sh("npx", ["tauri", "build"]);
}

const binary = [
  join(repo, "src-tauri", "target", "release", "openexpert-desktop"),
  join(repo, "src-tauri", "target", "release", "OpenExpert"),
].find((p) => existsSync(p));

if (!binary) {
  console.error("No desktop binary found. Run `npx tauri build` first (or drop --skip-build).");
  process.exit(1);
}

mkdirSync(binDir, { recursive: true });
mkdirSync(appsDir, { recursive: true });
mkdirSync(iconDir, { recursive: true });

const installedBinary = join(binDir, "openexpert-desktop");
copyFileSync(binary, installedBinary);
chmodSync(installedBinary, 0o755);

// Launcher: start the server and open the native window. Uses absolute paths
// (node + repo) so it works from a desktop launcher (rofi/wofi/fuzzel) whose
// PATH may not include ~/.local/bin. Logs to ~/.openexpert/desktop.log when not
// attached to a terminal.
const cliEntry = join(repo, "packages", "opencore", "bin", "opencore.js");
const nodeBin = process.execPath;
const logFile = join(home, ".openexpert", "desktop.log");
const launcher = join(binDir, "openexpert");
writeFileSync(
  launcher,
  `#!/usr/bin/env bash\n# SPDX-License-Identifier: MIT\n# Generated by scripts/install-desktop.mjs\nexport OPENEXPERT_DESKTOP_REPO="${repo}"\nmkdir -p "$HOME/.openexpert" 2>/dev/null || true\ncd "${repo}" 2>/dev/null || true\nif [ -t 1 ]; then\n  exec "${nodeBin}" "${cliEntry}" desktop "$@"\nelse\n  exec "${nodeBin}" "${cliEntry}" desktop "$@" >>"${logFile}" 2>&1\nfi\n`,
);
chmodSync(launcher, 0o755);

// Remove the previous capitalised launcher, if any.
const legacyLauncher = join(binDir, "OpenExpert");
if (existsSync(legacyLauncher)) rmSync(legacyLauncher, { force: true });

// The desktop entry uses the absolute launcher path (Exec + TryExec) so the
// application menu does not depend on PATH.
const desktopEntry = readFileSync(join(repo, "src-tauri", "OpenExpert.desktop"), "utf8").replace(
  /^Exec=.*$/m,
  `Exec=${launcher}\nTryExec=${launcher}`,
);
writeFileSync(join(appsDir, "openexpert.desktop"), desktopEntry);

const iconSource = join(repo, "public", "icon-source.png");
if (!existsSync(iconSource)) {
  console.error(`Missing icon source: ${iconSource}`);
  process.exit(1);
}
copyFileSync(iconSource, join(iconDir, "openexpert.png"));

// Refresh desktop/icon caches (best effort; tools may be absent).
const refresh = [
  ["update-desktop-database", [appsDir]],
  ["gtk-update-icon-cache", ["-f", "-t", hicolorDir]],
];
for (const [cmd, args] of refresh) {
  const r = spawnSync(cmd, args, { stdio: "ignore" });
  if (r.error) console.log(`  (skipped: ${cmd} not available)`);
}

console.log("\n✓ OpenExpert installed for the current user.");
console.log(`  Command:  openexpert`);
console.log(`  Window:   ${installedBinary}`);
console.log(`  Launcher: ${join(appsDir, "openexpert.desktop")}`);
