/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/expert'
import { Route as AuthenticatedExpertsRouteImport } from './routes/_authenticated/experts'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedIntegrationsProcessesRouteImport } from './routes/_authenticated/integrations.processes'
import { Route as AuthenticatedIntegrationsSourcesRouteImport } from './routes/_authenticated/integrations.sources'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertsRoute = AuthenticatedExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedIntegrationsProcessesRoute =
  AuthenticatedIntegrationsProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedIntegrationsSourcesRoute =
  AuthenticatedIntegrationsSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/experts': typeof AuthenticatedExpertsRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/experts': typeof AuthenticatedExpertsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/expert': typeof AuthenticatedExpertRoute
  '/_authenticated/experts': typeof AuthenticatedExpertsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/_authenticated/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/expert'
    | '/experts'
    | '/integrations'
    | '/users'
    | '/api/chat'
    | '/integrations/processes'
    | '/integrations/sources'
    | '/auth/google/callback'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/expert'
    | '/experts'
    | '/users'
    | '/api/chat'
    | '/integrations/processes'
    | '/integrations/sources'
    | '/auth/google/callback'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/expert'
    | '/_authenticated/experts'
    | '/_authenticated/integrations'
    | '/_authenticated/users'
    | '/api/chat'
    | '/_authenticated/integrations/processes'
    | '/_authenticated/integrations/sources'
    | '/auth/google/callback'
    | '/_authenticated/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expert': {
      id: '/_authenticated/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experts': {
      id: '/_authenticated/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof AuthenticatedExpertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/integrations/processes': {
      id: '/_authenticated/integrations/processes'
      path: '/processes'
      fullPath: '/integrations/processes'
      preLoaderRoute: typeof AuthenticatedIntegrationsProcessesRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/integrations/sources': {
      id: '/_authenticated/integrations/sources'
      path: '/sources'
      fullPath: '/integrations/sources'
      preLoaderRoute: typeof AuthenticatedIntegrationsSourcesRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedIntegrationsRouteChildren {
  AuthenticatedIntegrationsProcessesRoute: typeof AuthenticatedIntegrationsProcessesRoute
  AuthenticatedIntegrationsSourcesRoute: typeof AuthenticatedIntegrationsSourcesRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
}

const AuthenticatedIntegrationsRouteChildren: AuthenticatedIntegrationsRouteChildren =
  {
    AuthenticatedIntegrationsProcessesRoute:
      AuthenticatedIntegrationsProcessesRoute,
    AuthenticatedIntegrationsSourcesRoute:
      AuthenticatedIntegrationsSourcesRoute,
    AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  }

const AuthenticatedIntegrationsRouteWithChildren =
  AuthenticatedIntegrationsRoute._addFileChildren(
    AuthenticatedIntegrationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRoute
  AuthenticatedExpertsRoute: typeof AuthenticatedExpertsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedExpertRoute: AuthenticatedExpertRoute,
  AuthenticatedExpertsRoute: AuthenticatedExpertsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
