/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/expert'
import { Route as AuthenticatedExpertsRouteImport } from './routes/_authenticated/experts'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedIntegrationsProcessesRouteImport } from './routes/_authenticated/integrations.processes'
import { Route as AuthenticatedIntegrationsSourcesRouteImport } from './routes/_authenticated/integrations.sources'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings.about'
import { Route as AuthenticatedSettingsAdvancedRouteImport } from './routes/_authenticated/settings.advanced'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings.appearance'
import { Route as AuthenticatedSettingsChatRouteImport } from './routes/_authenticated/settings.chat'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertsRoute = AuthenticatedExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedIntegrationsProcessesRoute =
  AuthenticatedIntegrationsProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedIntegrationsSourcesRoute =
  AuthenticatedIntegrationsSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAdvancedRoute =
  AuthenticatedSettingsAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRoute,
} as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChatRoute =
  AuthenticatedSettingsChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/experts': typeof AuthenticatedExpertsRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/chat': typeof AuthenticatedSettingsChatRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/expert': typeof AuthenticatedExpertRoute
  '/experts': typeof AuthenticatedExpertsRoute
  '/api/chat': typeof ApiChatRoute
  '/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/chat': typeof AuthenticatedSettingsChatRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/expert': typeof AuthenticatedExpertRoute
  '/_authenticated/experts': typeof AuthenticatedExpertsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/integrations/processes': typeof AuthenticatedIntegrationsProcessesRoute
  '/_authenticated/integrations/sources': typeof AuthenticatedIntegrationsSourcesRoute
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/chat': typeof AuthenticatedSettingsChatRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/expert'
    | '/experts'
    | '/integrations'
    | '/settings'
    | '/api/chat'
    | '/integrations/processes'
    | '/integrations/sources'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/chat'
    | '/auth/google/callback'
    | '/integrations/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/expert'
    | '/experts'
    | '/api/chat'
    | '/integrations/processes'
    | '/integrations/sources'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/chat'
    | '/auth/google/callback'
    | '/integrations'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/activity'
    | '/_authenticated/expert'
    | '/_authenticated/experts'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/integrations/processes'
    | '/_authenticated/integrations/sources'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/advanced'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/chat'
    | '/auth/google/callback'
    | '/_authenticated/integrations/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expert': {
      id: '/_authenticated/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experts': {
      id: '/_authenticated/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof AuthenticatedExpertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/integrations/processes': {
      id: '/_authenticated/integrations/processes'
      path: '/processes'
      fullPath: '/integrations/processes'
      preLoaderRoute: typeof AuthenticatedIntegrationsProcessesRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/integrations/sources': {
      id: '/_authenticated/integrations/sources'
      path: '/sources'
      fullPath: '/integrations/sources'
      preLoaderRoute: typeof AuthenticatedIntegrationsSourcesRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/advanced': {
      id: '/_authenticated/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof AuthenticatedSettingsAdvancedRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/chat': {
      id: '/_authenticated/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof AuthenticatedSettingsChatRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedIntegrationsRouteChildren {
  AuthenticatedIntegrationsProcessesRoute: typeof AuthenticatedIntegrationsProcessesRoute
  AuthenticatedIntegrationsSourcesRoute: typeof AuthenticatedIntegrationsSourcesRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
}

const AuthenticatedIntegrationsRouteChildren: AuthenticatedIntegrationsRouteChildren =
  {
    AuthenticatedIntegrationsProcessesRoute:
      AuthenticatedIntegrationsProcessesRoute,
    AuthenticatedIntegrationsSourcesRoute:
      AuthenticatedIntegrationsSourcesRoute,
    AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  }

const AuthenticatedIntegrationsRouteWithChildren =
  AuthenticatedIntegrationsRoute._addFileChildren(
    AuthenticatedIntegrationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsAdvancedRoute: typeof AuthenticatedSettingsAdvancedRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsChatRoute: typeof AuthenticatedSettingsChatRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
  AuthenticatedSettingsAdvancedRoute: AuthenticatedSettingsAdvancedRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsChatRoute: AuthenticatedSettingsChatRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRoute
  AuthenticatedExpertsRoute: typeof AuthenticatedExpertsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedExpertRoute: AuthenticatedExpertRoute,
  AuthenticatedExpertsRoute: AuthenticatedExpertsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
